# Generated by Django 5.2.17 on 2026-08-20 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCustomSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='章節標題')),
                ('content', models.TextField(blank=True, default='', verbose_name='章節內容')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_sections', to='projects.project')),
            ],
            options={
                'ordering': ['project_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFeatureContentOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('system_design', '系統設計文件'), ('system_test', '系統測試文件'), ('system_install', '系統安裝文件'), ('training_deck', '教育訓練簡報')], max_length=30, verbose_name='文件類型')),
                ('body', models.TextField(blank=True, default='', verbose_name='覆寫內容文字')),
                ('bullets', models.JSONField(blank=True, default=list, verbose_name='覆寫條列項目')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_overrides', to='features.featurenode')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_overrides', to='projects.project')),
            ],
            options={
                'ordering': ['project_id', 'node_id', 'document_type'],
                'constraints': [models.UniqueConstraint(fields=('project', 'node', 'document_type'), name='unique_project_node_document_type_override')],
            },
        ),
    ]
