# Generated by Django 5.2.17 on 2026-08-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overrides', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcustomsection',
            options={'ordering': ['project_id', 'order', 'id'], 'verbose_name': '專案自訂章節', 'verbose_name_plural': '專案自訂章節'},
        ),
        migrations.AlterModelOptions(
            name='projectfeaturecontentoverride',
            options={'ordering': ['project_id', 'node_id', 'document_type'], 'verbose_name': '專案內容覆寫', 'verbose_name_plural': '專案內容覆寫'},
        ),
    ]
