# Generated by Django 5.2.17 on 2026-08-20 03:06

import django.db.models.deletion
import screenshots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenshotRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='截圖項目名稱')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshot_requirements', to='features.featurenode')),
            ],
            options={
                'ordering': ['node_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=screenshots.models._screenshot_upload_path, verbose_name='圖片')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('document_types', models.JSONField(default=list, verbose_name='套用文件類型')),
                ('is_custom', models.BooleanField(default=False, verbose_name='是否為客製版本')),
                ('caption', models.CharField(blank=True, default='', max_length=500, verbose_name='圖說')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='projects.project')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='screenshots.screenshotrequirement')),
            ],
            options={
                'ordering': ['requirement_id', 'is_custom', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_custom', False)), fields=('project', 'requirement'), name='unique_default_screenshot_per_requirement')],
            },
        ),
    ]
