# Generated by Django 5.2.17 on 2026-08-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectscreenshot',
            options={'ordering': ['requirement_id', 'is_custom', 'id'], 'verbose_name': '專案截圖', 'verbose_name_plural': '專案截圖'},
        ),
        migrations.AlterModelOptions(
            name='screenshotrequirement',
            options={'ordering': ['node_id', 'order', 'id'], 'verbose_name': '截圖需求', 'verbose_name_plural': '截圖需求'},
        ),
    ]
