# Generated by Django 5.2.17 on 2026-08-20 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='功能名稱')),
                ('description', models.TextField(blank=True, default='', verbose_name='功能說明')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='features.featurenode')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FeatureNodeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('system_design', '系統設計文件'), ('system_test', '系統測試文件'), ('system_install', '系統安裝文件'), ('training_deck', '教育訓練簡報')], max_length=30, verbose_name='文件類型')),
                ('body', models.TextField(blank=True, default='', verbose_name='內容文字')),
                ('bullets', models.JSONField(blank=True, default=list, verbose_name='條列項目')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='features.featurenode')),
            ],
            options={
                'ordering': ['node_id', 'document_type'],
                'constraints': [models.UniqueConstraint(fields=('node', 'document_type'), name='unique_node_document_type')],
            },
        ),
    ]
