# Generated by Django 5.2.17 on 2026-08-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurenode',
            options={'ordering': ['id'], 'verbose_name': '功能節點', 'verbose_name_plural': '功能節點'},
        ),
        migrations.AlterModelOptions(
            name='featurenodecontent',
            options={'ordering': ['node_id', 'document_type'], 'verbose_name': '功能節點內容', 'verbose_name_plural': '功能節點內容'},
        ),
    ]
