# Generated by Django 5.2.17 on 2026-08-23 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_alter_featurenode_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurenode',
            name='is_enabled',
        ),
    ]
