# Generated by Django 5.2.17 on 2026-08-20 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='客戶名稱')),
                ('project_name', models.CharField(max_length=200, verbose_name='專案名稱')),
                ('system_name', models.CharField(blank=True, default='', max_length=200, verbose_name='系統名稱')),
                ('system_url', models.CharField(blank=True, default='', max_length=500, verbose_name='系統網址')),
                ('system_version', models.CharField(blank=True, default='', max_length=100, verbose_name='系統版本')),
                ('acceptance_date', models.DateField(blank=True, null=True, verbose_name='驗收日期')),
                ('install_environment', models.CharField(blank=True, default='', max_length=200, verbose_name='安裝環境')),
                ('operating_system', models.CharField(blank=True, default='', max_length=200, verbose_name='作業系統')),
                ('database', models.CharField(blank=True, default='', max_length=200, verbose_name='資料庫')),
                ('server_location', models.CharField(blank=True, default='', max_length=200, verbose_name='伺服器位置')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='owner_user_id')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
