# Generated by Django 5.2.17 on 2026-08-23 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_alter_project_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_deleted',
        ),
    ]
