# Generated by Django 5.2.17 on 2026-08-20 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFeatureExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='features.featurenode')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_exclusions', to='projects.project')),
            ],
            options={
                'ordering': ['node_id'],
                'constraints': [models.UniqueConstraint(fields=('project', 'node'), name='unique_project_excluded_node')],
            },
        ),
        migrations.CreateModel(
            name='ProjectFeatureSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='features.featurenode')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_selections', to='projects.project')),
            ],
            options={
                'ordering': ['node_id'],
                'constraints': [models.UniqueConstraint(fields=('project', 'node'), name='unique_project_checked_node')],
            },
        ),
    ]
