# Generated by Django 5.2.17 on 2026-08-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfeatureexclusion',
            options={'ordering': ['node_id'], 'verbose_name': '專案功能排除', 'verbose_name_plural': '專案功能排除'},
        ),
        migrations.AlterModelOptions(
            name='projectfeatureselection',
            options={'ordering': ['node_id'], 'verbose_name': '專案功能勾選', 'verbose_name_plural': '專案功能勾選'},
        ),
    ]
