# Generated by Django 5.2.17 on 2026-08-20 04:19

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('system_design', '系統設計文件'), ('system_test', '系統測試文件'), ('system_install', '系統安裝文件'), ('training_deck', '教育訓練簡報')], max_length=30, verbose_name='文件類型')),
                ('output_format', models.CharField(choices=[('docx', 'DOCX'), ('pptx', 'PPTX')], default='docx', max_length=10, verbose_name='輸出格式')),
                ('content_snapshot', models.JSONField(verbose_name='內容快照')),
                ('file', models.FileField(upload_to=documents.models._generated_document_upload_path, verbose_name='產生的檔案')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='產生時間')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='projects.project')),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
            },
        ),
    ]
