# Generated by Django 5.2.17 on 2026-08-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generateddocument',
            options={'ordering': ['-generated_at', '-id'], 'verbose_name': '已產生文件', 'verbose_name_plural': '已產生文件'},
        ),
    ]
