# Generated by Django 5.2.17 on 2026-08-20 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPreviewSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('system_design', '系統設計文件'), ('system_test', '系統測試文件'), ('system_install', '系統安裝文件'), ('training_deck', '教育訓練簡報')], max_length=30, verbose_name='文件類型')),
                ('section_order', models.JSONField(blank=True, default=list, verbose_name='章節排序')),
                ('excluded_sections', models.JSONField(blank=True, default=list, verbose_name='本文件類型預覽層級排除的章節')),
                ('screenshot_selections', models.JSONField(blank=True, default=dict, verbose_name='本文件類型預覽層級手動指定的截圖')),
                ('caption_overrides', models.JSONField(blank=True, default=dict, verbose_name='本文件類型預覽層級的圖說覆蓋')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_settings', to='projects.project')),
            ],
            options={
                'ordering': ['project_id', 'document_type'],
                'constraints': [models.UniqueConstraint(fields=('project', 'document_type'), name='unique_project_document_type_preview_setting')],
            },
        ),
    ]
