# Generated by Django 5.2.17 on 2026-08-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpreviewsetting',
            options={'ordering': ['project_id', 'document_type'], 'verbose_name': '專案預覽設定', 'verbose_name_plural': '專案預覽設定'},
        ),
    ]
